# Generated by Django 5.2.6 on 2025-09-26 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='foto_documento',
        ),
        migrations.AddField(
            model_name='customuser',
            name='foto_documento_frente',
            field=models.ImageField(blank=True, null=True, upload_to='documentos/frente/'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='foto_documento_verso',
            field=models.ImageField(blank=True, null=True, upload_to='documentos/verso/'),
        ),
    ]
